In [1]:
import pandas as pd
import datetime

In [2]:
datos_camaras = pd.read_csv('datos_modelo_aforo.csv', sep=';').drop(['Unnamed: 0'], axis=1)

In [3]:
datos_camaras.head()

,FECHA,HORA,IDENTIFICADOR,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD,Festivo,dia_semana,mes
0,2021-01-01 0:00,0:00,PERM_PEA02_PM01,110.0,1,Centro,Calle Fuencarral,22,28004,Calle peatonal,40.422009,-3.700892,True,Friday,January
1,2021-01-01 0:00,0:00,PERM_PEA03_PM01,111.0,1,Centro,Calle San Bernardo,36,28015,Acera Pares,40.423803,-3.707379,True,Friday,January
2,2021-01-01 0:00,0:00,PERM_PEA04_PM01,15.0,1,Centro,Calle Hortaleza,18,28004,Acera Pares,40.421072,-3.700490,True,Friday,January
3,2021-01-01 0:00,0:00,PERM_PEA05_PM01,44.0,1,Centro,Carrera de San Jerónimo,6,28014,Acera Pares,40.416641,-3.701247,True,Friday,January
4,2021-01-01 0:00,0:00,PERM_PEA06_PM01,49.0,1,Centro,Calle Atocha,95,28012,Acera Impares,40.411109,-3.696471,True,Friday,January

In [4]:
datos_camaras['FECHA']=datos_camaras['FECHA'].astype(str)
datos_camaras["FECHA"]

0          2021-01-01 0:00
1          2021-01-01 0:00
2          2021-01-01 0:00
3          2021-01-01 0:00
4          2021-01-01 0:00
                ...
301763    2019-12-31 23:00
301764    2019-12-31 23:00
301765    2019-12-31 23:00
301766    2019-12-31 23:00
301767    2019-12-31 23:00
Name: FECHA, Length: 301768, dtype: object

In [5]:
datos_camaras['FECHA'] = datos_camaras['FECHA'].str.replace("-","/")
datos_camaras['FECHA']= datos_camaras['FECHA'].str.slice(0, 10)
datos_camaras["FECHA"]

0         2021/01/01
1         2021/01/01
2         2021/01/01
3         2021/01/01
4         2021/01/01
             ...
301763    2019/12/31
301764    2019/12/31
301765    2019/12/31
301766    2019/12/31
301767    2019/12/31
Name: FECHA, Length: 301768, dtype: object

In [6]:
datos_camaras['HORA']=datos_camaras['HORA'].astype(str)

In [7]:
datos_camaras['HORA']

0          0:00
1          0:00
2          0:00
3          0:00
4          0:00
          ...
301763    23:00
301764    23:00
301765    23:00
301766    23:00
301767    23:00
Name: HORA, Length: 301768, dtype: object

In [31]:
datos_camaras['FECHA']=datos_camaras['FECHA']+"T"+datos_camaras['HORA']+':00Z+0000'

In [32]:
datos_camaras['FECHA']

0           2021-01-01T0:00ZT0:00:00Z
1           2021-01-01T0:00ZT0:00:00Z
2           2021-01-01T0:00ZT0:00:00Z
3           2021-01-01T0:00ZT0:00:00Z
4           2021-01-01T0:00ZT0:00:00Z
                     ...
301763    2019-12-31T23:00ZT23:00:00Z
301764    2019-12-31T23:00ZT23:00:00Z
301765    2019-12-31T23:00ZT23:00:00Z
301766    2019-12-31T23:00ZT23:00:00Z
301767    2019-12-31T23:00ZT23:00:00Z
Name: FECHA, Length: 301768, dtype: object

In [33]:
datos_camaras['FECHA'] = datos_camaras['FECHA'].str.replace("/","-")

In [34]:
datos_camaras.head()

,FECHA,HORA,IDENTIFICADOR,PEATONES,NÚMERO_DISTRITO,DISTRITO,NOMBRE_VIAL,NÚMERO,CÓDIGO_POSTAL,OBSERVACIONES_DIRECCION,LATITUD,LONGITUD,Festivo,dia_semana,mes,momento
0,2021-01-01T0:00ZT0:00:00Z,0:00,PERM_PEA02_PM01,110.0,1,Centro,Calle Fuencarral,22,28004,Calle peatonal,40.422009,-3.700892,True,Friday,January,2021/01/01T0:00Z
1,2021-01-01T0:00ZT0:00:00Z,0:00,PERM_PEA03_PM01,111.0,1,Centro,Calle San Bernardo,36,28015,Acera Pares,40.423803,-3.707379,True,Friday,January,2021/01/01T0:00Z
2,2021-01-01T0:00ZT0:00:00Z,0:00,PERM_PEA04_PM01,15.0,1,Centro,Calle Hortaleza,18,28004,Acera Pares,40.421072,-3.700490,True,Friday,January,2021/01/01T0:00Z
3,2021-01-01T0:00ZT0:00:00Z,0:00,PERM_PEA05_PM01,44.0,1,Centro,Carrera de San Jerónimo,6,28014,Acera Pares,40.416641,-3.701247,True,Friday,January,2021/01/01T0:00Z
4,2021-01-01T0:00ZT0:00:00Z,0:00,PERM_PEA06_PM01,49.0,1,Centro,Calle Atocha,95,28012,Acera Impares,40.411109,-3.696471,True,Friday,January,2021/01/01T0:00Z

In [35]:
datos_camaras.to_csv("datos_carto.csv",sep=";")

In [36]:
print(datetime.datetime.now())

2022-05-25 19:38:33.442508

In [14]:
festivos=pd.read_excel('calendario.xls', index_col=0)  
festivos

,Día_semana,laborable / festivo / domingo festivo,Tipo de Festivo,Festividad
Día,,,,
2013-01-01,martes,festivo,Festivo nacional,Año Nuevo
2013-01-02,miércoles,laborable,NaN,NaN
2013-01-03,jueves,laborable,NaN,NaN
2013-01-04,viernes,laborable,NaN,NaN
2013-01-05,sábado,sábado,NaN,NaN
...,...,...,...,...
2022-12-27,martes,NaN,NaN,NaN
2022-12-28,miércoles,NaN,NaN,NaN
2022-12-29,jueves,NaN,NaN,NaN
2022-12-30,viernes,NaN,NaN,NaN
2022-12-31,sábado,NaN,NaN,NaN

In [15]:
festivos.index
#dtype: datetime64[ns]

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10',
               ...
               '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25',
               '2022-12-26', '2022-12-27', '2022-12-28', '2022-12-29',
               '2022-12-30', '2022-12-31'],
              dtype='datetime64[ns]', name='Día', length=3651, freq=None)